### ISSUE TITLE
_superEmit

### ISSUE THREAD

**Issue by hadwin2017** [alemures/fast-tcp#4]
Hi Alejandro:
   I'm confused when reading your source code, and I have a questions:
   In "Server.js", the Server object have a prototype function "_superEmit". Which object will it emit msg to ?
   Thank you!

**Comment by alemures** [comment]
Hi @hadwin2017 ,

The Server class is an EventEmitter so, users can listen to events on Server instances. Because I'm using the method Server#emit to send messages to client Sockets, i had to rename the inherited EventEmitter#emit into Server#_superEmit right before i implemented the custom Server#emit.

Server#_superEmit is only used to send events to implementors so, they can listen to those events using Server#on (inherited also from EventEmitter), the events are documented in the Server.js file.

 * @fires Server#listening
 * @fires Server#close
 * @fires Server#connection
 * @fires Server#error
